window.__DAILY_STOCK_REPORT__ = {
  "generatedAt": "2026-05-21T01:25:19+08:00",
  "generatedLabel": "2026-05-21 01:25",
  "title": "A股趋势股票日报",
  "subtitle": "趋势候选、资金热度、风险纪律与明日观察",
  "market": {
    "avgPct": 7.1,
    "upCount": 12,
    "downCount": 0,
    "aboveMa20Count": 12,
    "sampleCount": 12
  },
  "insight": {
    "headline": "今日改为趋势股票池：科技成长线强于固定自选池",
    "marketTone": "今天不再围绕原来的固定自选池做报告，而是切换为每日趋势扫描。全市场实时行情源在本次运行中多次抖动，因此本版由 Codex 结合本地项目数据与当日公开市场报道生成趋势候选。当前更值得跟踪的是半导体、AI算力、光通信这些资金识别度高的方向；策略上只做趋势候选，不做无条件买入建议，重点看次日是否继续放量、是否高位承接、是否出现板块共振。",
    "opportunities": [
      "半导体链：兆易创新、沪硅产业、中微公司代表存储、材料、设备三个分支，若次日仍有多只股票维持强势，说明科技线不是单点脉冲。",
      "AI算力链：工业富联、浪潮信息属于服务器硬件方向，适合观察大成交额趋势资金是否持续流入。",
      "光通信链：新易盛、中际旭创、德科立具备高弹性，适合做趋势强弱风向标，但要用更严格的回撤纪律处理。",
      "组合思路：优先跟踪板块共振中的龙头和中军，不追孤立涨幅；同一主题最多选择 1-2 只，避免相关性过高。"
    ],
    "risks": [
      "趋势候选不是买入清单。连续加速后的股票，一旦次日放量滞涨或高开低走，短线回撤会很快。",
      "本次全市场实时行情源有抖动，页面会注明候选来源；明日自动任务会继续尝试实时扫描并覆盖这份报告。",
      "半导体和光通信都属于高波动成长方向，适合用分批和止损，而不是一次性重仓。",
      "如果大盘成交额收缩、题材轮动过快，趋势股票容易从强势变成冲高回落，必须观察板块内是否仍有梯队。"
    ],
    "watchlist": [
      "兆易创新：观察涨停后次日是否有高位承接，若炸板或放量长上影，降低追踪优先级。",
      "中微公司/沪硅产业：作为半导体设备与材料方向观察项，关注是否能与兆易创新形成板块共振。",
      "新易盛/中际旭创：光模块趋势风向标，关注高位换手后是否继续维持趋势。",
      "工业富联/浪潮信息：AI服务器链中军，关注成交额和抗跌性，比单日涨幅更重要。",
      "明日确认条件：候选池中至少 3 只继续站强、主题内有新股补涨、成交额不明显萎缩，才把趋势等级上调。"
    ]
  },
  "configStatus": {
    "codexAi": true,
    "openai": false,
    "notify": false,
    "aiError": ""
  },
  "stocks": [
    {
      "code": "600584",
      "name": "长电科技",
      "date": "2026-05-21",
      "close": 66.22,
      "change": 5.41,
      "pctChg": 8.9,
      "amountText": "186.83亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 66.89,
      "low20": 59.77,
      "volatility20": null,
      "momentum5": 8.9,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 8.90%，成交额 186.83亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "300604",
      "name": "长川科技",
      "date": "2026-05-21",
      "close": 241.56,
      "change": 17.51,
      "pctChg": 7.82,
      "amountText": "90.49亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 249.77,
      "low20": 228.07,
      "volatility20": null,
      "momentum5": 7.82,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 7.82%，成交额 90.49亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "002371",
      "name": "北方华创",
      "date": "2026-05-21",
      "close": 656.0,
      "change": 36.3,
      "pctChg": 5.86,
      "amountText": "105.21亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 660.0,
      "low20": 614.0,
      "volatility20": null,
      "momentum5": 5.86,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 5.86%，成交额 105.21亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "002709",
      "name": "天赐材料",
      "date": "2026-05-21",
      "close": 58.0,
      "change": 3.56,
      "pctChg": 6.54,
      "amountText": "78.28亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 59.2,
      "low20": 54.0,
      "volatility20": null,
      "momentum5": 6.54,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 6.54%，成交额 78.28亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "300274",
      "name": "阳光电源",
      "date": "2026-05-21",
      "close": 167.2,
      "change": 9.82,
      "pctChg": 6.24,
      "amountText": "192.99亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 170.89,
      "low20": 156.1,
      "volatility20": null,
      "momentum5": 6.24,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 6.24%，成交额 192.99亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "002008",
      "name": "大族激光",
      "date": "2026-05-21",
      "close": 144.54,
      "change": 7.55,
      "pctChg": 5.51,
      "amountText": "88.17亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 145.9,
      "low20": 135.68,
      "volatility20": null,
      "momentum5": 5.51,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 5.51%，成交额 88.17亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "301511",
      "name": "德福科技",
      "date": "2026-05-21",
      "close": 109.6,
      "change": 9.21,
      "pctChg": 9.17,
      "amountText": "37.90亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 111.37,
      "low20": 97.11,
      "volatility20": null,
      "momentum5": 9.17,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 9.17%，成交额 37.90亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "300316",
      "name": "晶盛机电",
      "date": "2026-05-21",
      "close": 56.85,
      "change": 4.74,
      "pctChg": 9.1,
      "amountText": "36.34亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 57.58,
      "low20": 51.51,
      "volatility20": null,
      "momentum5": 9.1,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 9.10%，成交额 36.34亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "002837",
      "name": "英维克",
      "date": "2026-05-21",
      "close": 108.41,
      "change": 6.01,
      "pctChg": 5.87,
      "amountText": "74.73亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 110.48,
      "low20": 99.0,
      "volatility20": null,
      "momentum5": 5.87,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 5.87%，成交额 74.73亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "002156",
      "name": "通富微电",
      "date": "2026-05-21",
      "close": 62.28,
      "change": 3.42,
      "pctChg": 5.81,
      "amountText": "122.88亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 63.84,
      "low20": 58.55,
      "volatility20": null,
      "momentum5": 5.81,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 5.81%，成交额 122.88亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "601208",
      "name": "东材科技",
      "date": "2026-05-21",
      "close": 51.49,
      "change": 3.67,
      "pctChg": 7.67,
      "amountText": "45.04亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 51.74,
      "low20": 47.25,
      "volatility20": null,
      "momentum5": 7.67,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 7.67%，成交额 45.04亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "688313",
      "name": "仕佳光子",
      "date": "2026-05-21",
      "close": 184.9,
      "change": 11.59,
      "pctChg": 6.69,
      "amountText": "59.18亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 188.46,
      "low20": 167.8,
      "volatility20": null,
      "momentum5": 6.69,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 6.69%，成交额 59.18亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    }
  ]
};
