window.__DAILY_STOCK_REPORT__ = {
  "generatedAt": "2026-06-06T02:00:39+08:00",
  "generatedLabel": "2026-06-06 02:00",
  "title": "A股趋势股票日报",
  "subtitle": "趋势候选、资金热度、风险纪律与明日观察",
  "market": {
    "avgPct": 7.66,
    "upCount": 12,
    "downCount": 0,
    "aboveMa20Count": 12,
    "sampleCount": 12
  },
  "insight": {
    "headline": "2026-06-06 趋势资金聚焦通信硬件、卫星链与先进制造补涨",
    "marketTone": "今日趋势候选共 12 只，平均涨幅约 7.50%。高分样本集中在通信硬件、PCB/显示材料、卫星军工与消费电子制造，说明资金仍在围绕硬科技景气链做扩散交易；同时前排成交额明显放大，属于趋势资金主导而非纯题材脉冲。次日更应关注核心股分歧后的承接质量，避免在一致性高开时被动追价。",
    "opportunities": [
      "通信硬件与连接链共振最明显，信维通信(300136)、烽火通信(600498)、金安国纪(002636)成交额与涨幅同步走强，若前排高开后仍有换手承接，这条线仍是趋势跟踪首选。",
      "卫星军工方向由航天电子(600879)和中国卫星(600118)形成前后排联动，若板块次日继续放量且回落不破强势区，说明资金愿意继续做主题强化。",
      "先进制造和消费电子链有补涨扩散迹象，沃格光电(603773)、蓝思科技(300433)、亚翔集成(603929)说明主线开始向设备材料与制造环节传导，可优先观察分歧后最先企稳的中军品种。"
    ],
    "risks": [
      "多只候选股收盘接近日内高位，次日若出现明显高开但量能无法继续放大，容易从趋势加速切换为短线兑现，纪律上不追一致性加速板。",
      "主线集中度偏高，一旦通信硬件或卫星前排转弱，后排补涨股回撤速度通常更快。单票宜控制仓位，跌破前一日强势平台或日内承接低点应及时止损。",
      "若次日市场无法维持硬科技与制造链共振，而转为无主线快轮动，趋势池会迅速收缩，届时应减少追涨并等待核心股二次确认。"
    ],
    "watchlist": [
      "信维通信(300136)：看百亿成交额能否继续维持，重点观察高开后的换手承接与是否继续充当通信链强度锚。",
      "航天电子(600879)：观察卫星军工方向能否延续前排封强或高位震荡承接，若放量不破强势区则有利于板块持续。",
      "烽火通信(600498)：关注通信设备中军能否承接住分歧，若回踩后重新放量上攻，说明主线仍有扩散空间。",
      "沃格光电(603773)：作为高弹性补涨样本，重点看次日是否缩量滞涨；若放量续强，代表材料链跟风意愿增强。",
      "蓝思科技(300433)：作为大成交额消费电子制造观察点，若继续稳步走强，有助于确认趋势资金并未只停留在题材前排。"
    ]
  },
  "configStatus": {
    "codexAi": true,
    "openai": false,
    "notify": false,
    "aiError": ""
  },
  "stocks": [
    {
      "code": "300136",
      "name": "信维通信",
      "date": "2026-06-06",
      "close": 106.33,
      "change": 8.33,
      "pctChg": 8.5,
      "amountText": "133.20亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 108.98,
      "low20": 97.0,
      "volatility20": null,
      "momentum5": 8.5,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 8.50%，成交额 133.20亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "600879",
      "name": "航天电子",
      "date": "2026-06-06",
      "close": 21.54,
      "change": 1.83,
      "pctChg": 9.29,
      "amountText": "53.62亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 21.68,
      "low20": 20.0,
      "volatility20": null,
      "momentum5": 9.29,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 9.29%，成交额 53.62亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "600498",
      "name": "烽火通信",
      "date": "2026-06-06",
      "close": 56.48,
      "change": 3.73,
      "pctChg": 7.07,
      "amountText": "118.33亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 58.03,
      "low20": 52.0,
      "volatility20": null,
      "momentum5": 7.07,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 7.07%，成交额 118.33亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "300346",
      "name": "南大光电",
      "date": "2026-06-06",
      "close": 57.03,
      "change": 4.44,
      "pctChg": 8.44,
      "amountText": "65.34亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 60.61,
      "low20": 50.65,
      "volatility20": null,
      "momentum5": 8.44,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 8.44%，成交额 65.34亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "603773",
      "name": "沃格光电",
      "date": "2026-06-06",
      "close": 132.4,
      "change": 10.0,
      "pctChg": 8.17,
      "amountText": "47.47亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 134.64,
      "low20": 122.3,
      "volatility20": null,
      "momentum5": 8.17,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 8.17%，成交额 47.47亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "002636",
      "name": "金安国纪",
      "date": "2026-06-06",
      "close": 58.16,
      "change": 4.16,
      "pctChg": 7.7,
      "amountText": "51.75亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 59.4,
      "low20": 52.8,
      "volatility20": null,
      "momentum5": 7.7,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 7.70%，成交额 51.75亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "600118",
      "name": "中国卫星",
      "date": "2026-06-06",
      "close": 84.95,
      "change": 4.67,
      "pctChg": 5.82,
      "amountText": "63.76亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 85.0,
      "low20": 80.5,
      "volatility20": null,
      "momentum5": 5.82,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 5.82%，成交额 63.76亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "600869",
      "name": "远东股份",
      "date": "2026-06-06",
      "close": 28.51,
      "change": 2.01,
      "pctChg": 7.58,
      "amountText": "49.48亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 29.15,
      "low20": 26.15,
      "volatility20": null,
      "momentum5": 7.58,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 7.58%，成交额 49.48亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "300503",
      "name": "昊志机电",
      "date": "2026-06-06",
      "close": 81.77,
      "change": 6.68,
      "pctChg": 8.9,
      "amountText": "31.56亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 83.97,
      "low20": 70.0,
      "volatility20": null,
      "momentum5": 8.9,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 8.90%，成交额 31.56亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "603929",
      "name": "亚翔集成",
      "date": "2026-06-06",
      "close": 170.09,
      "change": 14.09,
      "pctChg": 9.03,
      "amountText": "20.52亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 171.35,
      "low20": 153.0,
      "volatility20": null,
      "momentum5": 9.03,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 9.03%，成交额 20.52亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "600707",
      "name": "彩虹股份",
      "date": "2026-06-06",
      "close": 11.71,
      "change": 0.76,
      "pctChg": 6.94,
      "amountText": "46.34亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 12.05,
      "low20": 10.4,
      "volatility20": null,
      "momentum5": 6.94,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 6.94%，成交额 46.34亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "300433",
      "name": "蓝思科技",
      "date": "2026-06-06",
      "close": 45.61,
      "change": 1.97,
      "pctChg": 4.51,
      "amountText": "102.99亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 47.79,
      "low20": 41.99,
      "volatility20": null,
      "momentum5": 4.51,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 4.51%，成交额 102.99亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    }
  ]
};
