window.__DAILY_STOCK_REPORT__ = {
  "generatedAt": "2026-05-27T23:14:57+08:00",
  "generatedLabel": "2026-05-27 23:14",
  "title": "A股趋势股票日报",
  "subtitle": "趋势候选、资金热度、风险纪律与明日观察",
  "market": {
    "avgPct": 7.08,
    "upCount": 12,
    "downCount": 0,
    "aboveMa20Count": 12,
    "sampleCount": 12
  },
  "insight": {
    "headline": "2026-05-27 趋势候选偏轮动：封测/光通信与电力、消费同场博弈",
    "marketTone": "本次趋势扫描共 12 只入池，平均涨跌幅 7.08%，中位数 7.34%。候选分布呈‘轮动+题材交织’：一边是半导体封测/电子元件、光通信/光学方向的活跃度提升，另一边电力与白酒等偏防守品种也进入视野。这类结构下更适合‘确认后跟随’：看次日是否出现板块梯队（核心+跟随），以及强势股能否在分歧中缩量守位。",
    "opportunities": [
      "封测/电子元件：以华天科技(002185)、风华高科(000636)为观察点，优先跟踪放量不滞涨与回撤缩量的强趋势形态。",
      "光通信/光器件：关注源杰科技(688498)、天孚通信(300394)的承接强度；若板块出现‘核心带动跟随’，再提高进攻仓位。",
      "风格轮动下的防守腿：大唐发电(601991)等偏稳方向若能维持量价上台阶，可作为回撤期的节奏对冲。",
      "执行要点：一致性高开不追，等待换手后回踩确认；单票不重仓，优先做‘组合跟随’而不是押注单一题材。"
    ],
    "risks": [
      "轮动行情最怕追高：高开低走/放量滞涨通常意味着情绪见顶，优先减仓而不是补仓。",
      "题材线波动大：设置硬止损（跌破平台/前低）与时间止损（两天不走强则退出），避免被动‘熬回本’。",
      "跨题材共振不足时，候选池可能快速降温：若次日无法形成板块梯队，策略从进攻切回防守，等待二次确认。"
    ],
    "watchlist": [
      "华天科技(002185)｜半导体封测｜涨幅 7.93%，成交额 244.48亿，收盘靠近日内高位，量价强度较好。 次日观察：是否继续放量承接、回撤是否缩量、是否守住今日关键价区。",
      "源杰科技(688498)｜光器件/光通信｜涨幅 7.96%，成交额 84.77亿，收盘靠近日内高位，量价强度较好。 次日观察：是否继续放量承接、回撤是否缩量、是否守住今日关键价区。",
      "天孚通信(300394)｜光通信｜涨幅 5.37%，成交额 221.53亿，收盘靠近日内高位，量价强度较好。 次日观察：是否继续放量承接、回撤是否缩量、是否守住今日关键价区。",
      "风华高科(000636)｜电子元件｜涨幅 6.04%，成交额 91.21亿，收盘靠近日内高位，量价强度较好。 次日观察：是否继续放量承接、回撤是否缩量、是否守住今日关键价区。",
      "大唐发电(601991)｜电力｜涨幅 7.68%，成交额 71.66亿，收盘靠近日内高位，量价强度较好。 次日观察：是否继续放量承接、回撤是否缩量、是否守住今日关键价区。",
      "XD舍得酒(600702)｜白酒｜涨幅 9.59%，成交额 9.80亿，收盘靠近日内高位，量价强度较好。 次日观察：是否继续放量承接、回撤是否缩量、是否守住今日关键价区。"
    ]
  },
  "configStatus": {
    "codexAi": true,
    "openai": false,
    "notify": false,
    "aiError": ""
  },
  "stocks": [
    {
      "code": "600330",
      "name": "天通股份",
      "date": "2026-05-27",
      "close": 31.21,
      "change": 2.35,
      "pctChg": 8.14,
      "amountText": "78.07亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 31.75,
      "low20": 28.0,
      "volatility20": null,
      "momentum5": 8.14,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 8.14%，成交额 78.07亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "688498",
      "name": "源杰科技",
      "date": "2026-05-27",
      "close": 1124.0,
      "change": 82.9,
      "pctChg": 7.96,
      "amountText": "84.77亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 1138.88,
      "low20": 1046.59,
      "volatility20": null,
      "momentum5": 7.96,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 7.96%，成交额 84.77亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "002185",
      "name": "华天科技",
      "date": "2026-05-27",
      "close": 20.15,
      "change": 1.48,
      "pctChg": 7.93,
      "amountText": "244.48亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 20.54,
      "low20": 19.4,
      "volatility20": null,
      "momentum5": 7.93,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 7.93%，成交额 244.48亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "601991",
      "name": "大唐发电",
      "date": "2026-05-27",
      "close": 7.71,
      "change": 0.55,
      "pctChg": 7.68,
      "amountText": "71.66亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 7.8,
      "low20": 7.0,
      "volatility20": null,
      "momentum5": 7.68,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 7.68%，成交额 71.66亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "000636",
      "name": "风华高科",
      "date": "2026-05-27",
      "close": 44.22,
      "change": 2.52,
      "pctChg": 6.04,
      "amountText": "91.21亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 44.99,
      "low20": 41.72,
      "volatility20": null,
      "momentum5": 6.04,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 6.04%，成交额 91.21亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "603773",
      "name": "沃格光电",
      "date": "2026-05-27",
      "close": 99.99,
      "change": 8.45,
      "pctChg": 9.23,
      "amountText": "40.44亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 100.69,
      "low20": 96.77,
      "volatility20": null,
      "momentum5": 9.23,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 9.23%，成交额 40.44亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "300394",
      "name": "天孚通信",
      "date": "2026-05-27",
      "close": 428.61,
      "change": 21.85,
      "pctChg": 5.37,
      "amountText": "221.53亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 444.64,
      "low20": 401.83,
      "volatility20": null,
      "momentum5": 5.37,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 5.37%，成交额 221.53亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "300433",
      "name": "蓝思科技",
      "date": "2026-05-27",
      "close": 40.28,
      "change": 1.8,
      "pctChg": 4.68,
      "amountText": "84.63亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 41.0,
      "low20": 37.45,
      "volatility20": null,
      "momentum5": 4.68,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 4.68%，成交额 84.63亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "002273",
      "name": "水晶光电",
      "date": "2026-05-27",
      "close": 42.05,
      "change": 2.75,
      "pctChg": 7.0,
      "amountText": "52.00亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 42.88,
      "low20": 39.0,
      "volatility20": null,
      "momentum5": 7.0,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 7.00%，成交额 52.00亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "600105",
      "name": "永鼎股份",
      "date": "2026-05-27",
      "close": 48.5,
      "change": 2.22,
      "pctChg": 4.8,
      "amountText": "94.93亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 49.88,
      "low20": 45.28,
      "volatility20": null,
      "momentum5": 4.8,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 4.80%，成交额 94.93亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "603601",
      "name": "再升科技",
      "date": "2026-05-27",
      "close": 21.39,
      "change": 1.31,
      "pctChg": 6.52,
      "amountText": "56.57亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 22.0,
      "low20": 19.39,
      "volatility20": null,
      "momentum5": 6.52,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 6.52%，成交额 56.57亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    },
    {
      "code": "600702",
      "name": "XD舍得酒",
      "date": "2026-05-27",
      "close": 44.13,
      "change": 3.86,
      "pctChg": 9.59,
      "amountText": "9.80亿",
      "volumeRatio": 1.0,
      "turnover": null,
      "ma5": null,
      "ma10": null,
      "ma20": null,
      "aboveMa20": true,
      "high20": 44.3,
      "low20": 39.66,
      "volatility20": null,
      "momentum5": 9.59,
      "momentum20": null,
      "dataSource": "akshare A-share spot",
      "sparkline": [],
      "bars": [],
      "advice": "趋势候选",
      "sentimentScore": null,
      "trendPrediction": "趋势跟踪",
      "analysisSummary": "涨幅 9.59%，成交额 9.80亿，收盘靠近日内高位，量价强度较好。",
      "rawResult": ""
    }
  ]
};
